### ISSUE TITLE
modhub page does not exist.

### ISSUE THREAD

**Issue by whatLETMEFUCKINGSIGNINGITHUBFUCKYOU** [SamsDRGMods/SimpleQOL#10]
in the simpleQOL modhub page, it says no page is registered.

**To Reproduce**
Steps to reproduce the behavior: h key

**Comment by samamstar** [comment]
Is this issue still present? Sorry for the long reply time, I forgot to watch the repo

**Comment by samamstar** [comment]
Closed for lack of response; If the issue is in fact still persistent please open a new issue
