### ISSUE TITLE
Request: Supply Drop available next to Nitra counter

### ISSUE THREAD

**Issue by GoldMath** [SamsDRGMods/SimpleQOL#14]
Hello, thanks again for you nice collection.

The idea is to add a simple math next to the Nitra counter in the Team Depository. 
Example, you have 182 Nitra, it will be display as: 
> Nitra              x2   182

![Capture3](https://user-images.githubusercontent.com/7282547/174076450-5172ba5d-e300-4bd2-8d4b-3f772f67aa28.jpg)

Complication would be make it compatible with mods who change the actually Nitra required and then adapt the formula.

Regards,

**Comment by samamstar** [comment]
I'll bite! Solid idea

**Comment by samamstar** [comment]
Fixed in https://github.com/SamsDRGMods/SimpleQOL/commit/0dc3051e7c3c71bcf0d75ebd06d22478d8cedfa9
