### ISSUE TITLE
Select a Mission for the mod list don't deactivate "Friends Only"

### ISSUE THREAD

**Issue by GoldMath** [SamsDRGMods/SimpleQOL#15]
Hello, 

When you select a mission from the mod "Mission list" it don't deactivate the "Friends Only" (compared from the Mission Terminal).

Minor suggest: Rename "Mission list" into "Mission List", looks better for tabs.

**Comment by samamstar** [comment]
I don't follow. Are you saying that:

1. When selecting a mission the lobby is switched from public to friends only
2. When selecting a mission the lobby is switched from friends only to public
3. When selecting a mission the lobby privacy is unchanged, but you would like it to be

**Comment by GoldMath** [comment]
That would be the **"3."** because it's how the game act without using your mod. 
But there is a small variant, meaning it should need an additional customization option.

Here is how it behave without your mod:
1. Launch the Game
2. You in the SpaceRig, press ESC, you already set to "Friends Only"
3. Use the DRG Mission Terminal, launch a mission as "Host: Public"
4. Press ESC, you no longer set to "Friends Only", able to have people join-in.

Your mod actually only behave like you using the "Host: Private" option in the Mission Terminal.

That's mean the mod should have an option to auto Host as Public or Private.
