### ISSUE TITLE
i hope have only recall  sentries(2)  Q^Q

### ISSUE THREAD

**Issue by bbaaam** [SamsDRGMods/SimpleQOL#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samamstar** [comment]
What? Could you elaborate please, I am having difficulties understanding the title

**Comment by samamstar** [comment]
Closing.

I have no idea what you're asking for. Please fill out a the description if you request a feature in the future

**Comment by bbaaam** [comment]
[image: FSD-Win64-Shipping_gyOtMGLAai.png]
i need prioritize sentry two
[image: image.png]

samamstar ***@***.***> 于2022年7月3日周日 20:54写道：

**Comment by bbaaam** [comment]
i need prioritize sentry two

**Comment by samamstar** [comment]
I fail to see how that would be useful. How does the prioritize sentry one function not fulfill your needs?

**Comment by bbaaam** [comment]
[image: image.png]When placing I want to use prioritize sentry two to be
the stretch of the center of the circle, now prioritize sentry one makes
sentry two the center of the beginning, which means I always need a little
more process to set successfully

samamstar ***@***.***> 于2022年7月4日周一 09:24写道：
