### ISSUE TITLE
Allow for prioritizing either sentry one or two

### ISSUE THREAD

**Issue by bbaaam** [SamsDRGMods/SimpleQOL#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by samamstar** [comment]
I fail to see how that would be useful. It would serve an identical purpose to the existing prioritize sentry 2 function

**Comment by bbaaam** [comment]
turret arc !

**Comment by samamstar** [comment]
I think I see... I'll look into reworking the sentry priority feature.

**Comment by bbaaam** [comment]
Thank you.

samamstar ***@***.***> 于2022年7月5日周二 06:53写道：

**Comment by samamstar** [comment]
You know, I was putting more thought into this and do not think it's something I want to implement. To select sentry 2 just double tap "Equip 4"

**Comment by bbaaam** [comment]
turret arc need

samamstar ***@***.***> 于2022年7月4日周一 09:27写道：

**Comment by samamstar** [comment]
Since this thread I actually implemented several new keybinds to select sentries. Hopefully one of these fit your needs
