### ISSUE TITLE
Reload cancel issues

### ISSUE THREAD

**Issue by Dwight-Reed** [SamsDRGMods/SimpleQOL#20]
**Describe the bug**
Canceling reload does not work before switching weapons after loading into a mission
Canceling sometimes stops working for a few reloads, then starts working again

**To Reproduce**
Only can reliably reproduce the first part, 2nd part I've only really noticed on engineer w/ LOK-1 (but I don't use many other weapons that reload canceling is useful on, so I could be wrong)

**Expected behavior**
Reload canceling to work properly

**Additional context**
Tried to figure out how to reproduce it, I have no idea

**Comment by samamstar** [comment]
I have made an update that should address this issue, but it will require testing in multiplayer.

**Comment by samamstar** [comment]
Testing complete; closing.
