### ISSUE TITLE
Hover boots macro doesn't work well in multiplayer

### ISSUE THREAD

**Issue by ImmortalZypther** [SamsDRGMods/SimpleQOL#22]
**Describe the bug**
In singleplayer, the hover boots macro works fine, but once you get into multiplayer the macro becomes very inconsistent. I've had games where it works and others where it doesn't, it seems completely random compared to every other macro.

**To Reproduce**
Join multiplayer and attempt to use the hover boots macro. It won't work regardless of how much you press or how long you hold it for.

**Expected behavior**
Hover boots will activate.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by samamstar** [comment]
Well shoot I meant to fix that; should just take a longer delay. I'll get to it next week hopefully
