### ISSUE TITLE
SimpleQOL's resupply counter doesn't work if Ammo Resupply Indicator mod is installed too

### ISSUE THREAD

**Issue by Hyperly26** [SamsDRGMods/SimpleQOL#25]
**Describe the bug**
This bug prevents both of the mods to work. More precisely, everything about SimpleQOL except the resupply indicator works. I can still use custom bindings but the resupply counter doesn't work.

If I join a random lobby (doesn't matter whether I join while in space rig or during the mission), sometimes both of the mods work and sometimes they don't. Same with Deep Dives. If they work in one of the missions, then they may not work in another mission of a Deep Dive.
If I host my own lobby, then both of the mods ALWAYS work.

The other mod in question: https://drg.old.mod.io/ammo-resupply-indicator

**To Reproduce**
Steps to reproduce the behavior: Subscribe to both of them and join a random lobby. You will see that it will sometimes work and sometimes won't.

**Expected behavior**
Both of the mods should do what they were supposed to do. 

**Screenshots**

**Additional context**
Unsubscribing from either one of them makes the other mod work all the time.
Unsubscribing from all the mods I've subscribed to and then subscribing one by one didn't fix the issue either.
If I disable the resupply counter through the Mod Hub, it doesn't fix the issue. The other mod still won't work.
This issue wasn't present before the SimpleQOL update that added the resupply counter.

**Comment by samamstar** [comment]
WontFix. I cannot guarantee, or often even facilitate, compatibility with other mods

TBH I've been meaning to fold a similar feature to ammo resupply indicator into SimpleQOL.

**Comment by Hyperly26** [comment]
Understandable. Thanks for replying anyway. 
Also, I must say that adding a feature similar to ammo resupply indicator would be amazing because of mod limit. It means one fewer mod that you subscribe to.
