### ISSUE TITLE
Recalling a specific sentry doesn't work when sentry 1 was previously recalled

### ISSUE THREAD

**Issue by jerryskye** [SamsDRGMods/SimpleQOL#31]
**Describe the bug**
After recalling only sentry one using the mod's hotkey and placing it again, the sentries are both named `Sentry #2`. This breaks hotkeys that recall a specific sentry:
* "Recall sentry one" hotkey does nothing
* "Recall sentry two" hotkey recalls both sentries 🤔
* "Recall closest/furthers sentry" hotkeys also recall both sentries

This might actually be a bug in the game itself and not the mod 😃 let me know what you think :wink:

**To Reproduce**
1. Place two sentries
1. Recall sentry one
1. Place it again
1. Try recalling either one with hotkeys

**Expected behavior**
Recalling a specific sentry actually recalls it with no funny behavior

**Screenshots**
Both sentries named `Sentry #2`, how weird! :grin:

![20221007020324_1](https://user-images.githubusercontent.com/15806405/194441445-bd432f4a-fa31-49ac-8b18-06dc1e075cc0.jpg)

**Additional context**
Recalling a manually selected sentry works fine, which makes this bug a little less annoying 🙂

**Comment by samamstar** [comment]
Unfortunately, this is a bug with the base game and I don't have any idea of how to work around it. It's perfectly reproducible using base game mechanics, but I doubt this will rate highly on GSG's bug tracker

**Comment by jerryskye** [comment]
Makes sense, thanks for this wonderful mod btw 🙇‍♂️
