### ISSUE TITLE
Game crashes upon attempting to edit any bind

### ISSUE THREAD

**Issue by Aluorine** [SamsDRGMods/SimpleQOL#41]
**Describe the bug**
The game crashes when selecting any custom bind option and pressing any button. Same thing for attempting to remove a bind.

**To Reproduce**
1. Left-click on any custom bind option.
2. Press any button, as if attempting to set it for that bind.

Alternative:
1. Right-click on any already set bind.

**Expected behavior**
Not crashing, preferably

**Screenshots**
Pressing any button in this situation would cause the game to crash (and it did when I pressed the screenshot button):
![image](https://user-images.githubusercontent.com/41546969/222952824-c5480494-94c3-4437-969f-683cd12f2bb5.png)

Pressing right-click in this situation would have the same effect:
![image](https://user-images.githubusercontent.com/41546969/222952861-d430c978-ce1d-482e-a2cd-8dd16715233c.png)

**Comment by AydenWilson** [comment]
I have this same problem.

**Comment by samamstar** [comment]
This is being caused by DRGLib, which I also wrote. I'm looking into it, but haven't been taking much time to mod lately. No promises on how long a fix will take

**Comment by sorasin** [comment]
> This is being caused by DRGLib, which I also wrote. I'm looking into it, but haven't been taking much time to mod lately. No promises on how long a fix will take

Please take your time, I appreciate all that you do for this mod and many others.

**Comment by samamstar** [comment]
Been fixed for a while, forgot to close
