### ISSUE TITLE
game crashes on keybind setup

### ISSUE THREAD

**Issue by waeteet** [SamsDRGMods/SimpleQOL#42]
game crashes upon setting a keybind to trigger a perk. after the crash, no keybind is set.

to reproduce, try setting a keybind to a shortcut for a perk

the game crashes with the crash screen showing the note that you have mods installed and they might be causing the crash

**Comment by SmoothMemes22** [comment]
Same problem! Happens with any rebind.

**Comment by AydenWilson** [comment]
Same for me.

**Comment by samamstar** [comment]
Duplicate of #41
