### ISSUE TITLE
Crashes game on changing a keybind in the tweaks tab

### ISSUE THREAD

**Issue by Tyranicas** [SamsDRGMods/SimpleQOL#43]
**Describe the bug**
When trying to change a keybind in the tweaks tab of SimpleQOL using modhub, the game crashes

**To Reproduce**
open mod hub, try to bind a key using the interface

**Expected behavior**

Keybind gets changed

**Screenshots**

**Additional context**

**Comment by samamstar** [comment]
Duplicate of #42

**Comment by samamstar** [comment]
Whoops I meant # 41
