### ISSUE TITLE
Crash to desktop when attempting to set a Custom Dash Binding

### ISSUE THREAD

**Issue by theoreminegaming** [SamsDRGMods/SimpleQOL#44]
**Describe the bug**
Attempting to use the Dash perk rebind function at all results in a crash

**To Reproduce**
Open the mod manager menu to access settings, click on the custom dash binding button, press any key

**Expected behavior**
binding will update to the selected key

**Screenshots**

**Additional context**

**Comment by samamstar** [comment]
Duplicate of #42

**Comment by samamstar** [comment]
Whoops I meant #41
