### ISSUE TITLE
Add a reset binds option.

### ISSUE THREAD

**Issue by ICEYNDERP** [SamsDRGMods/SimpleQOL#48]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a suggestion.

**Describe the solution you'd like**
In the menu, you can only rebind to buttons on your input device (keyboard and mouse to be precise), It would be nice to reset the keybinds back to "Empty" as an option for those that dont want to use that feature at that time or disable those keybinds.

**Comment by samamstar** [comment]
Right click on the Input Key Selector
