### ISSUE TITLE
Is this being maintained anymore?

### ISSUE THREAD

**Issue by QuentinMcCarthy** [SamsDRGMods/SimpleQOL#54]
I hate to be "that guy" but as I posted on the mod.io page, this hasn't seemingly been touched in 2 years and there's a lot of bugs and feature requests that haven't even been responded to. Every day this mod seems to get a new quirk, particularly in conjunction with other mods that add features that - again, this mod fails to add or consider on request.

**Comment by samamstar** [comment]
I do *genuinely* intend to revisit this project, but I've had very little luck getting it to build on Linux. I'm thinking I'll start dual booting my laptop for it
