### ISSUE TITLE
mission list doesn't support non-latin characters

### ISSUE THREAD

**Issue by TyleRxYan** [SamsDRGMods/SimpleQOL#8]
**Describe the bug**
as title

**To Reproduce**
change the game language to Chinese (and Korean I guess? not test yet)

**Expected behavior**
properly display. It should be like upper-right in the screenshot

**Screenshots**
![20220428055820_1](https://user-images.githubusercontent.com/12888698/165638131-81a55345-ad03-43ac-a14f-36f87177af09.jpg).

**Additional context**
I barely use it, so take your time. 
and I think the function should integrate in the map, or become a replacement of the Rig HUD with hazard bonus display, and it will be even better if the list is also clickable.

**Comment by samamstar** [comment]
Noted. I think this should be an easy fix, I just need to enable a fallback font with support for those characters... I think? I don't play with fonts much :P

**Comment by samamstar** [comment]
Fixed by DRGLib 4.4.0

**Comment by TyleRxYan** [comment]
![image](https://user-images.githubusercontent.com/12888698/176981627-b209e836-0395-4710-b34b-1d052d0cf309.png)
well...it is fixed ......  particatilly... 
I‘ve checked the drglib's changelog, the fallback font seems can not fully cover the simplified-chinese and traditional-chinese characteres, and it shouldn't because of size, so I still recommand to assign specific font depend on the UI language, ie. SimHei for simplified chinese in this case, or the font come with vanilla game.

**Comment by samamstar** [comment]
Well shoot; I went through all the effort of adding noto sans ch and forgot to add it as a sub-font family. Will fix soon; likely this weekend.

**Comment by samamstar** [comment]
I have no idea how fonts work. As far as I can tell, the font in DRGLib is missing specific glyphs in the CJK unified ideographs space; but fixing it is just not something I really have suitable knowledge to fix. 

Believe me, it's not for lack of trying, but I've been banging my head against the wall for the last 5 days and have made little to no progress. If you absolutely need this fixed, DRGLib is open source and I'm always happy to accept contributions :)

**Comment by samamstar** [comment]
I'll see about using the ingame fonts; but that has it's own issues that I'll need to figure out

**Comment by samamstar** [comment]
Ok I gave it one more try and I think I got it; finally.

**Comment by TyleRxYan** [comment]
thanks for your hard work, I appreciate that. 
Rock'n Stone, Brother!
