### ISSUE TITLE
Preferred hazard level not functioning correctly

### ISSUE THREAD

**Issue by NoShotz** [SamsDRGMods/SimpleQOL#9]
**Describe the bug**
If you set the preferred hazard level while in the space rig it will set it accordingly in the mission select UI, however this does not persist between missions or game restarts/shutdowns.

**To Reproduce**
Set the preferred hazard level, and complete a mission or restart the game and check the hazard level selected in the mission select screen 

**Expected behavior**
Setting should persist between missions and game restarts/shutdowns.

**Comment by samamstar** [comment]
Oh, that's a great point. I'll re-work how I apply the preferred difficulty with the next update. Also, I should figure out how to enable notifications, this is the first time I've seen that people have been adding issues! Thanks for your interest in SimpleQOL

**Comment by samamstar** [comment]
Fixed in https://github.com/SamsDRGMods/SimpleQOL/commit/e714593c3d157cac8d46d034e724dfc04e2947d4 .

Difficulty will now be set upon entering the Spacerig every time
